routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Calendar\CalendarController;
use App\Http\Controllers\Calendar\EventsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\References\DepartmentController;
use App\Http\Controllers\References\JobStatusController;
use App\Http\Controllers\References\PositionController;
use App\Http\Controllers\References\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->middleware('auth')->name('home');
Route::resource('/articles', ArticleController::class)->middleware('auth');
Route::resource('/users', UserController::class)->middleware('auth');
Route::prefix('/catalogs')->group(function () {
    Route::resource('/departments', DepartmentController::class)->except(['create', 'edit', 'show'])
    ->middleware('auth');
    Route::resource('/positions', PositionController::class)->except(['create', 'edit', 'show'])->middleware('auth');
    Route::resource('/job_statuses', JobStatusController::class)->except(['create', 'edit', 'show'])
    ->middleware('auth');
    Route::resource('/roles', RoleController::class)->except(['show'])->middleware('auth');
    Route::resource('/tasks', CalendarController::class)->except(['show'])->middleware('auth');
    Route::get('tasks/events', [CalendarController::class, 'events'])->middleware('auth');
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Models\Scopes\LatestScope;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Article extends Model
{
    use HasFactory;

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    public static function booted()
    {
        static::addGlobalScope(new LatestScope());
    }

    /**
     * Для массового назначения
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'body',
        'published_at',
        'user_id',
    ];

    /**
     * Столбцы для Carbon
     *
     * @var array<int, string>
     */
    protected $dates = [
        'published_at'
    ];

    /**
     * Мутатор для даты
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function publishedAt(): Attribute
    {
        return Attribute::make(
            get: fn ($value) =>Carbon::parse($value)->format('d.m.Y H:i'),
            set: fn ($value) =>Carbon::createFromFormat('d.m.Y H:i', $value)
        );
    }

    /**
     * Локальный скоуп для отображения уже опубликованных статей
     *
     * @param $query
     */
    public function scopePublished($query)
    {
        $query->where('published_at', '<=', Carbon::now());
    }

    /**
     * Локальный скоуп для еще не опубликованных записей
     *
     * @param $query
     * @return void
     */
    public function scopeUnpublished($query): void
    {
        $query->where('published_at', '>=', Carbon::now());
    }

    /**
     * Отношение к пользователю
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Отношение к тегам
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Services\ArticleService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Создание контроллера
     *
     * @param \App\Services\ArticleService $service
     * @return void
     */
    public function __construct(ArticleService $service)
    {
        $this->service = $service;
    }

    /**
     * Главная страница со всеми статьями
     *
     * @param Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\View\View
     */
    public function index(Request $request): View
    {
        return $this->service->index($request);
    }

    /**
     * Просмотр отдельной статьи
     *
     * @param \App\Models\Article $article Модель статьи
     * @return \Illuminate\Contracts\View\View
     */
    public function show(Article $article): View
    {
        return $this->service->show($article);
    }

    /**
     * Страница создания статьи
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create(): View
    {
        return $this->service->create();
    }

    /**
     * Сохранение статью в базу данных
     *
     * @param \App\Http\Requests\ArticleRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ArticleRequest $request): RedirectResponse
    {
        return $this->service->store($request->validated());
    }

    /**
     * Страница редактирования статьи
     *
     * @param \App\Models\Article $article Модель статьи
     * @return \Illuminate\Contracts\View\View
     */
    public function edit(Article $article): View
    {
        return $this->service->edit($article);
    }

    /**
     * Сохранение отредактированной статьи в базу данных
     *
     * @param \App\Http\Requests\ArticleRequest $request
     * @param \App\Models\Article $article Модель статьи
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ArticleRequest $request, Article $article): RedirectResponse
    {
        return $this->service->update($request->validated(), $article);
    }
}

resources/views/articles/form.blade.php
@extends('adminlte::page')

@section('title', 'Статьи')

@section('content_header')
    <h1>{{ __('article.formTitle', ['title' => $title, 'article' => $article->title ?? '']) }}</h1>
@stop

@section('content')
    <form action="{{ $route }}" method="post">
        @csrf
        @method($method ?? null)
        <x-adminlte-card theme="dark" theme-mode="outline">
            <x-adminlte-input type="text" name="title" label="{{ __('article.title') }}" placeholder="Lorem  ipsum dolor" 
            id="title" value="{{ $article->title ?? old('title') }}"/>

            <x-adminlte-textarea name="body" id="body" placeholder="Lorem  ipsum dolor" label="{{ __('article.body') }}"
            cols="30" rows="10">
                {{ $article->body ?? old('body') }}
            </x-adminlte-textarea>

            @php
                $config = ['format' => 'DD.MM.YYYY HH:mm'];
            @endphp
            <x-adminlte-input-date name="published_at" value="{{ $published_at->format('d.m.Y H:i') }}" :config="$config" label="Дата публикации:"/>

            <x-adminlte-select2 id="tags" name="tags[]" label="{{ __('article.tags') }}" multiple="multiple">
                <x-slot name="prependSlot">
                    <div class="input-group-text bg-gradient-black">
                        <i class="fas fa-tag"></i>
                    </div>
                </x-slot>
                @foreach ($tags as $tag)
                    @if (isset($article) && $article->tags->contains($tag) || collect(old("tags"))->contains($tag->id))
                        <option value={{ $tag->id }} selected>{{ $tag->name }}</option>
                    @else
                        <option value={{ $tag->id }}>{{ $tag->name }}</option>
                    @endif
                @endforeach
            </x-adminlte-select2>

            <x-adminlte-button type="submit" label="{{ $submitButtonText }}" theme="outline-success" class="form-control"/>
        </x-adminlte-card>
    </form>
@endsection

@section('plugins.TempusDominusBs4', true)
@section('plugins.Select2', true)

resources/views/articles/index.blade.php
@extends('adminlte::page')

@section('title', 'Статьи')

@section('content_header')
    @include('flash::message')
    <h1>{{ __('article.mainTitle') }}</h1>
@stop

@section('content')
    @can('create', App\Models\Article::class)
        <a href={{ route('articles.create') }} class="btn btn-outline-dark">{{ __('article.add') }}</a>
    @endcan
    <hr>
    <div class="row">
        @foreach ($articles as $article)
            <div class="col-md-4">
                <x-adminlte-card title="{{ $article->title }}" theme="dark">
                    {{ __('article.creator', ['creator' => $article->user->name]) }}
                    <div class="body">{{ $article->body }}</div>
                    <a href="{{ route('articles.show', $article->id) }}" class="link-dark">{{ __('article.full') }}</a>
                </x-adminlte-card>
            </div>
        @endforeach
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script>
        $('div.alert').not('.alert-important').delay(3000).slideUp(300);
    </script>
@stop

resources/views/articles/show.blade.php
@extends('adminlte::page')

@section('title', 'Статьи')

@section('content_header')
    <h1>{{ $article->title }}</h1>
    {{ __('article.published', ['published' => $article->published_at]) }}
@stop

@section('content')
    {{-- @if ($loggedUser == $article->user_id) --}}
    @unless (Auth::user()->hasRole('admin'))
        @isAbleToAndOwns('articles-update', $article)
            <a href={{ route('articles.edit', $article->id) }} class="btn btn-outline-dark">{{ __('article.edit') }}</a>
        @endOwns
    @else
    <a href={{ route('articles.edit', $article->id) }} class="btn btn-outline-dark">{{ __('article.edit') }}</a>

    @endunless
    {{-- @endif --}}
    <hr>
    <article>
        {{ $article->body }}
    </article>
    @unless ($article->tags->isEmpty())
        <h5>{{ __('article.tags') }}</h5>
        <ul>
            @foreach ($article->tags as $tag)
                <li><a href={{ route('articles.index', ['tag' => $tag->name]) }} class="list-group-item-action">{{ $tag->name }}</a></li>
            @endforeach
        </ul>
    @endunless
@endsection